name: ExtraWGBlockRestricter
main: ru.dreamland.ExtraWGBlockRestricter.ExtraWGBlockRestricterPlugin
version: ${project.version}
api-version: "1.21"
authors: [ "DJ_DarkLucky" ]
description: "WorldGuard extension to allow/deny block types per region (no WGCustomFlags)."
website: "https://github.com/dreamland-mc"
load: STARTUP
depend: [ WorldGuard ]

commands:
  ewgbr:
    description: "Admin commands for ExtraWGBlockRestricter"
    usage: "/ewgbr reload | version"
    permission: extrawgblockrestricter.admin
    aliases: [ extrawgbr, wgbr ]

permissions:
  extrawgblockrestricter.reload:
    description: "Allow to reload config"
    default: op

permissions:
  wgblockrestricter.ignore:
    description: "Bypass ExtraWGBlockRestricter checks"
    default: op
