name: ExtraWGBlockRestricter
main: ru.dreamland.ExtraWGBlockRestricter.ExtraWGBlockRestricterPlugin
version: 1.0.2-SNAPSHOT
api-version: "1.21"
authors: [ "DJ_DarkLucky" ]
description: "WorldGuard extension to allow/deny block types per region (no WGCustomFlags)."
website: "https://github.com/dreamland-mc"
load: STARTUP
depend: [ WorldGuard ]

permissions:
  wgblockrestricter.ignore:
    description: "Bypass ExtraWGBlockRestricter checks"
    default: op
